---
title: "Introduction"
---

The All of Us Research Program by the NIH aims to gather data from one million or more participants in the United States to foster research and conversation in how to improve health and build targeted interventions. Many types of data are collected including surveys, electronic health records, genomic data, and blood and urine tests. In this study, we aim to look at the part of the All of Us cohort that responded to the social determinants of health survey, which has self-reported scores of stress (derived from Cohen’s Perceived Stress Scale), loneliness (derived from UCLA Loneliness Scale), social support (derived from RAND MOS Social Support Survey Instrument), social cohesion (Social Cohesion Neighborhood Scale), and neighborhood disorder (Ross-Mirowsky Perceived Neighborhood Disorder Scale). It is a cross-sectional view of total of 57,365 respondents. We hypothesize that self-reported scores of loneliness will be associated with those of stress. We will explore the strength of that association in comparison to the other scores. The other covariates accounted for are age, sex at birth, sexual orientation, race/ethnicity, education, income, birthplace, home ownership, marital status, and health insurance status. As we want to account for confounding in the relationship between loneliness score and stress score, we will conduct correlation analyses and linear regression analysis.  
